customhost = "trainingdb.cvb006rbnfyp.us-east-2.rds.amazonaws.com"
customuser = "admin"
custompass = "passW0rd"
customdb = "TrainingDB"
custombucket = "trainingbucketsigma"
customregion = "us-east-2"
