customhost = "learningdb.cvb006rbnfyp.us-east-2.rds.amazonaws.com"
customuser = "learner"
custompass = "learnerpassword"
customdb = "learnerdb"
custombucket = "lernerbucket"
customregion = "us-east-2"
