customhost = "learningdb.cvb006rbnfyp.us-east-2.rds.amazonaws.com"
customuser = "learner"
custompass = "learnerpassword"
customdb = "learningdb"
custombucket = "addempmentor"
customregion = "us-east-1"
